name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: tianon/actions/checkout/composite@f7414637108a155a422f9894dc1e0a9990892dfc # HEAD
      - uses: tianon/actions/setup-go@f7414637108a155a422f9894dc1e0a9990892dfc # HEAD
        with:
          go-version-file: go.mod

      - run: gofmt -s -w .
      - run: go mod tidy
      - run: go generate ./...
      # make sure fmt, tidy, and generate didn't leave any uncommitted changes behind
      - run: git diff --exit-code

      - run: go vet ./...

      - name: go-licenses check
        run: go run github.com/google/go-licenses@v1.6.0 check ./...

      - name: staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@v0.7.0 ./...

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@v1.3.0 ./...

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containerd:
          - 1.7.32
          - 2.0.9
          - 2.1.8
          - 2.2.4
          - 2.3.1
      fail-fast: false
    steps:
      - uses: tianon/actions/checkout/composite@f7414637108a155a422f9894dc1e0a9990892dfc # HEAD
      - uses: tianon/actions/setup-go@f7414637108a155a422f9894dc1e0a9990892dfc # HEAD
        with:
          go-version-file: go.mod

      - run: sudo apt-get install --no-install-recommends fuse3 qemu-user-static

      - name: download containerd ${{ matrix.containerd }}
        env:
          CONTAINERD_VERSION: ${{ matrix.containerd }}
        run: |
          dpkgArch="$(dpkg --print-architecture)"
          case "$dpkgArch" in
            amd64) arch='amd64' ;;
            arm64) arch='arm64' ;;
            *) echo >&2 "error: unsupported architecture '$dpkgArch'"; exit 1 ;;
          esac
          tarball="containerd-${CONTAINERD_VERSION}-linux-${arch}.tar.gz"
          url="https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/${tarball}"
          cd /tmp
          curl -fsSL "$url" -o "$tarball"
          case "${CONTAINERD_VERSION}-${arch}" in
            1.7.32-amd64) sha256='4db81bc7c67ec5e5e38ec43f287e1eab6962035cd1f4a904694700ca40698b03' ;;
            1.7.32-arm64) sha256='631e7079dba58806e5a03158773030e4ac63c69343afe02e5419fb848485569c' ;;
            2.0.9-amd64)  sha256='3d2dc5e1f47888b4f8fa30fabf7f1b8ea20e1572c85e20557a3bb8bab81a54a3' ;;
            2.0.9-arm64)  sha256='fa582638e396f6182348142d642ce65d2efd68f01751d16310446fc8f15fddb2' ;;
            2.1.8-amd64)  sha256='ad2ed5bca4839109ec271e3ee0285abf36bec450956c5d59a31f1a980e8d71a9' ;;
            2.1.8-arm64)  sha256='c7c3d64fafbaccb4fb0143c82402db7d6c781e776d818a60fa0df94807814149' ;;
            2.2.4-amd64)  sha256='62e77f6294e432dca5b56ad7e7d6085b5bbb526ebba0a51d832714f9b04cfdfd' ;;
            2.2.4-arm64)  sha256='d0897c8e27c96a7b7d4c73e9b278ea9f559dda619d497d88b323a528bd1412c3' ;;
            2.3.1-amd64)  sha256='628448bd973610c656c1cbea8e88b32fafd85b23cc1aa4a3372eb7198478c054' ;;
            2.3.1-arm64)  sha256='46a83603a850f3916ca7c942310daaf82ed17773a85b1d431e92d4a541e46d0d' ;;
            *) echo >&2 "error: no checksum for containerd ${CONTAINERD_VERSION} ${arch}"; exit 1 ;;
          esac
          sha256sum --check --strict <<<"${sha256}  ${tarball}"
          sudo tar --extract --file "$tarball" --directory /usr/local/bin/ --strip-components=1

          [ "$(command -v containerd)" = '/usr/local/bin/containerd' ]
          [ "$(command -v ctr)" = '/usr/local/bin/ctr' ]

          sudo mkdir --parents /etc/systemd/system/containerd.service.d
          sudo tee /etc/systemd/system/containerd.service.d/execstart.conf << 'EOF'
          [Service]
          ExecStart=
          ExecStart=/usr/local/bin/containerd
          EOF

          {
            printf '%s\n' 'imports = ["/etc/containerd/conf.d/*.toml"]'
            containerd config default | grep --invert-match '^imports'
          } | sudo tee /etc/containerd/config.toml > /dev/null
          sudo mkdir --parents /etc/containerd/conf.d

          trap "$(printf 'sudo systemctl status --lines=0 containerd || :; sudo journalctl -u containerd --since %q || :' "$(date '+%Y-%m-%d %H:%M:%S')")" ERR
          sudo systemctl daemon-reload
          sudo systemctl restart containerd
          sudo ctr version

      - name: docker config
        run: |
          jq --null-input --tab '{
            #"containerd": "/run/containerd/containerd.sock", # already configured via --containerd=/run/containerd/containerd.sock in docker.service -- generates "unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: containerd: (from flag: /run/containerd/containerd.sock, from file: /run/containerd/containerd.sock)" which is some classic Docker
            "features": { "containerd-snapshotter": true },
          }' | sudo tee /etc/docker/daemon.json

          trap "$(printf 'sudo systemctl status --lines=0 docker || :; sudo journalctl -u docker --since %q || :' "$(date '+%Y-%m-%d %H:%M:%S')")" ERR
          sudo systemctl restart docker
          docker version

      - name: go test
        run: go test -race -count=1 ./...

      - run: go build -o containerd-snapshotter-tarfs .

      - name: start snapshotter
        run: |
          sudo mkdir --parents /run/containerd-snapshotter-tarfs
          sudo "$PWD/containerd-snapshotter-tarfs" > /tmp/snapshotter.log 2>&1 &
          for i in $(seq 30); do
            if [ -S /run/containerd-snapshotter-tarfs/snapshotter.sock ]; then
              break
            fi
            sleep 1
            [ "$i" -lt 30 ] || { echo >&2 'error: timed out waiting for snapshotter'; exit 1; }
          done

      - name: containerd config
        env:
          CONTAINERD_VERSION: ${{ matrix.containerd }}
        run: |
          sudo tee /etc/containerd/conf.d/tarfs.toml << 'EOF'
          [proxy_plugins.tarfs]
            type = "snapshot"
            address = "/run/containerd-snapshotter-tarfs/snapshotter.sock"

          [[plugins."io.containerd.transfer.v1.local".unpack_config]]
            snapshotter = "tarfs"
            platform = "linux"
          EOF
          case "$CONTAINERD_VERSION" in
            2.0.*)
              # containerd v2.0.x predates check_platform_supported, breaking cross-arch pulls with a custom snapshotter unless we are more specific in the config
              sudo head -3 /etc/containerd/conf.d/tarfs.toml | sudo tee /etc/containerd/conf.d/tarfs.toml.new
              sudo mv /etc/containerd/conf.d/tarfs.toml.new /etc/containerd/conf.d/tarfs.toml
              sudo tee /etc/containerd/conf.d/tarfs-c8d-2.0.toml <<'EOF'
          [[plugins."io.containerd.transfer.v1.local".unpack_config]]
            snapshotter = "tarfs"
            platform = "linux/amd64"

          [[plugins."io.containerd.transfer.v1.local".unpack_config]]
            snapshotter = "tarfs"
            platform = "linux/arm64"
            differ = "walking"
          EOF
              ;;
          esac

          trap "$(printf 'sudo systemctl status --lines=0 containerd || :; sudo journalctl -u containerd --since %q || :' "$(date '+%Y-%m-%d %H:%M:%S')")" ERR
          sudo systemctl restart containerd
          sudo ctr version

          jq --tab '."storage-driver" = "tarfs"' /etc/docker/daemon.json | sudo tee /etc/docker/daemon.json.new
          sudo mv /etc/docker/daemon.json.new /etc/docker/daemon.json
          trap "$(printf 'sudo systemctl status --lines=0 docker || :; sudo journalctl -u docker --since %q || :' "$(date '+%Y-%m-%d %H:%M:%S')")" ERR
          sudo systemctl restart docker
          docker version

      - run: sudo ctr images pull --snapshotter tarfs docker.io/tianon/true:oci
      - name: mount tianon/true:oci
        run: |
          sudo mkdir --parents /mnt/true
          sudo ctr images mount --snapshotter tarfs docker.io/tianon/true:oci /mnt/true
          test -f /mnt/true/true
          /mnt/true/true
          sudo ctr images unmount /mnt/true

      - run: sudo ctr images pull --snapshotter tarfs docker.io/library/bash:latest
      - name: mount bash:latest
        run: |
          sudo mkdir --parents /mnt/bash
          sudo ctr images mount --snapshotter tarfs docker.io/library/bash:latest /mnt/bash
          test -f /mnt/bash/usr/local/bin/bash
          grep containerd-snapshotter-tarfs /proc/mounts
          sudo ctr images unmount /mnt/bash

      - name: ctr run bash:latest (FUSE)
        run: |
          sudo ctr run --rm --snapshotter tarfs docker.io/library/bash:latest fuse-check \
            grep containerd-snapshotter-tarfs /proc/mounts

      - run: sudo ctr images pull --snapshotter tarfs --platform linux/arm64/v8 docker.io/library/bash:latest
      - name: ctr run bash:latest linux/arm64/v8
        run: |
          output="$(sudo ctr run --rm --snapshotter tarfs --platform linux/arm64/v8 docker.io/library/bash:latest arm64-test apk --print-arch)"
          echo "$output"
          [ "$output" = 'aarch64' ]

      - name: badtars
        run: |
          for tag in \
            badtars-duplicate-members \
            badtars-empty-filename \
            badtars-html \
            badtars-invalid-utf8 \
            badtars-invalid-whiteout \
            badtars-missing-contents \
            badtars-newline \
            badtars-overlong-utf8 \
          ; do
            sudo ctr images pull --snapshotter tarfs "docker.io/tianon/test:$tag" || continue
            sudo mkdir --parents "/mnt/$tag"
            sudo ctr images mount --snapshotter tarfs "docker.io/tianon/test:$tag" "/mnt/$tag" || continue
            sudo ctr images unmount "/mnt/$tag" || :
          done

      - name: sanity check after badtars
        run: |
          sudo mkdir --parents /mnt/true-final
          sudo ctr images mount --snapshotter tarfs docker.io/tianon/true:oci /mnt/true-final
          test -f /mnt/true-final/true
          /mnt/true-final/true
          sudo ctr images unmount /mnt/true-final

      - run: docker pull docker.io/library/bash:latest

      - name: docker run bash:latest (FUSE)
        run: docker run --rm docker.io/library/bash:latest grep containerd-snapshotter-tarfs /proc/mounts

      - name: docker run bash:latest linux/arm64/v8
        run: |
          output="$(docker run --rm --platform linux/arm64/v8 docker.io/library/bash:latest apk --print-arch)"
          [ "$output" = 'aarch64' ]

      - name: docker commit
        run: |
          docker run --name tarfs-commit-test bash:latest sh -c 'grep containerd-snapshotter-tarfs /proc/mounts > /tarfs.txt'
          docker commit tarfs-commit-test tarfs-commit-image
          docker rm tarfs-commit-test
          docker run --rm tarfs-commit-image cat /tarfs.txt

      - name: docker build (classic)
        run: |
          DOCKER_BUILDKIT=0 docker build --tag tarfs-classic-image - << 'EOF'
          FROM bash:latest
          RUN grep containerd-snapshotter-tarfs /proc/mounts > /tarfs.txt
          EOF
          docker run --rm tarfs-classic-image cat /tarfs.txt

      - name: docker build (buildkit)
        run: |
          DOCKER_BUILDKIT=1 docker build --tag tarfs-buildkit-image - << 'EOF'
          FROM bash:latest
          RUN grep containerd-snapshotter-tarfs /proc/mounts > /tarfs.txt
          EOF
          docker run --rm tarfs-buildkit-image cat /tarfs.txt

      - name: snapshotter log
        run: sudo cat /tmp/snapshotter.log
        if: failure()
